from app import app, db
from app.models import Item

i1 = Item(name='padded', type='armor', category='light')
i2 = Item(name='leather', type='armor', category='light')
i3 = Item(name='studded leather', type='armor', category='light')
i4 = Item(name='hide', type='armor', category='medium')
i5 = Item(name='chain shirt', type='armor', category='medium')
i6 = Item(name='scale mail', type='armor', category='medium')
i7 = Item(name='breastplate', type='armor', category='medium')
i8 = Item(name='half plate', type='armor', category='medium')
i9 = Item(name='ring mail', type='armor', category='heavy')
i10 = Item(name='chain mail', type='armor', category='heavy')
i11 = Item(name='splint', type='armor', category='heavy')
i12 = Item(name='plate', type='armor', category='heavy')
i13 = Item(name='shield', type='armor', category='shield')
i14 = Item(name='club', type='weapon', category='melee, simple')
i15 = Item(name='dagger', type='weapon', category='melee, simple')
i16 = Item(name='greatclub', type='weapon', category='melee, simple')
i17 = Item(name='hammer, light', type='weapon', category='melee, simple')
i18 = Item(name='handaxe', type='weapon', category='melee, simple')
i19 = Item(name='javelin', type='weapon', category='melee, simple')
i20 = Item(name='mace', type='weapon', category='melee, simple')
i21 = Item(name='quarterstaff', type='weapon', category='melee, simple')
i22 = Item(name='sickle', type='weapon', category='melee, simple')
i23 = Item(name='spear', type='weapon', category='melee, simple')
i24 = Item(name='crossbow, light', type='weapon', category='ranged, simple')
i25 = Item(name='dart', type='weapon', category='ranged, simple')
i26 = Item(name='shortbow', type='weapon', category='ranged, simple')
i27 = Item(name='sling', type='weapon', category='ranged, simple')
i28 = Item(name='battleaxe', type='weapon', category='melee, martial')
i29 = Item(name='flail', type='weapon', category='melee, martial')
i30 = Item(name='glaive', type='weapon', category='melee, martial')
i31 = Item(name='greataxe', type='weapon', category='melee, martial')
i32 = Item(name='greatsword', type='weapon', category='melee, martial')
i33 = Item(name='halberd', type='weapon', category='melee, martial')
i34 = Item(name='lance', type='weapon', category='melee, martial')
i35 = Item(name='longsword', type='weapon', category='melee, martial')
i36 = Item(name='maul', type='weapon', category='melee, martial')
i37 = Item(name='morningstar', type='weapon', category='melee, martial')
i38 = Item(name='pike', type='weapon', category='melee, martial')
i39 = Item(name='rapier', type='weapon', category='melee, martial')
i40 = Item(name='scimitar', type='weapon', category='melee, martial')
i41 = Item(name='shortsword', type='weapon', category='melee, martial')
i42 = Item(name='trident', type='weapon', category='melee, martial')
i43 = Item(name='war pick', type='weapon', category='melee, martial')
i44 = Item(name='warhammer', type='weapon', category='melee, martial')
i45 = Item(name='whip', type='weapon', category='melee, martial')
i46 = Item(name='blowgun', type='weapon', category='ranged, martial')
i47 = Item(name='crossbow, hand', type='weapon', category='ranged, martial')
i48 = Item(name='crossbow, heavy', type='weapon', category='ranged, martial')
i49 = Item(name='longbow', type='weapon', category='ranged, martial')
i50 = Item(name='net', type='weapon', category='ranged, martial')
i51 = Item(name='arrow (20)', type='ammunition')
i52 = Item(name='blowgun needles (50)', type='ammunition')
i53 = Item(name='crossbow bolts (20)', type='ammunition')
i54 = Item(name='sling bullets (20)', type='ammunition')
i55 = Item(name='crystal', type='arcane focus')
i56 = Item(name='orb', type='arcane focus')
i57 = Item(name='rod', type='arcane focus')
i58 = Item(name='staff', type='arcane focus')
i59 = Item(name='wond', type='arcane focus')
i60 = Item(name='sprig of mistletoe', type='druidic focus')
i61 = Item(name='totem', type='druidic focus')
i62 = Item(name='wooden staff', type='druidic focus')
i63 = Item(name='yew wond', type='druidic focus')
i64 = Item(name='amulet', type='holy symbol')
i65 = Item(name='emblem', type='holy symbol')
i66 = Item(name='reliquary', type='holy symbol')
i67 = Item(name='abacus', type='other')
i68 = Item(name='acid (vial)', type='other')
i69 = Item(name='alchemist\'s fire (Flask)', type='other')
i70 = Item(name='antitoxin (vial)', type='other')
i71 = Item(name='backpack', type='other')
i72 = Item(name='ball bearings (bag of 1,000)', type='other')
i73 = Item(name='barrel', type='other')
i74 = Item(name='basket', type='other')
i75 = Item(name='bedroll', type='other')
i76 = Item(name='bell', type='other')
i77 = Item(name='blanket', type='other')
i78 = Item(name='block and tackle', type='other')
i79 = Item(name='book', type='other')
i80 = Item(name='bottle, glass', type='other')
i81 = Item(name='bucket', type='other')
i82 = Item(name='caltrops (bag of 20)', type='other')
i83 = Item(name='candle', type='other')
i84 = Item(name='case, crossbow bolt', type='other')
i85 = Item(name='case, map or scroll', type='other')
i86 = Item(name='chain (10 feet)', type='other')
i87 = Item(name='chalk (1 piece)', type='other')
i88 = Item(name='chest', type='other')
i89 = Item(name='climber\'s kit', type='other')
i90 = Item(name='clothes, common', type='other')
i91 = Item(name='clothes, costume', type='other')
i92 = Item(name='clothes, fine', type='other')
i93 = Item(name='clothes, traveler\'s', type='other')
i94 = Item(name='component pouch', type='other')
i95 = Item(name='crowbar', type='other')
i96 = Item(name='fishing tackle', type='other')
i97 = Item(name='flask or tankard', type='other')
i98 = Item(name='grappling hook', type='other')
i99 = Item(name='hammer', type='other')
i100 = Item(name='hammer, sledge', type='other')
i101 = Item(name='healer\'s kit', type='other')
i102 = Item(name='holy water', type='other')
i103 = Item(name='hourglass', type='other')
i104 = Item(name='hunting trap', type='other')
i105 = Item(name='ink (1 ounce bottle)', type='other')
i106 = Item(name='ink pen', type='other')
i107 = Item(name='jug or pitcher', type='other')
i108 = Item(name='ladder (10-foot)', type='other')
i109 = Item(name='lamp', type='other')
i110 = Item(name='lantern, bullseye', type='other')
i111 = Item(name='lantern, hooded', type='other')
i112 = Item(name='lock', type='other')
i113 = Item(name='magnifying glass', type='other')
i114 = Item(name='manacles', type='other')
i115 = Item(name='mess kit', type='other')
i116 = Item(name='mirror, steel', type='other')
i117 = Item(name='oil (flask)', type='other')
i118 = Item(name='paper (one sheet)', type='other')
i119 = Item(name='parchment (one sheet)', type='other')
i120 = Item(name='perfume (vial)', type='other')
i121 = Item(name='pick, miner\'s', type='other')
i122 = Item(name='piton', type='other')
i123 = Item(name='poison, basic (vial)', type='other')
i124 = Item(name='pole (10-foot)', type='other')
i125 = Item(name='pot, iron', type='other')
i126 = Item(name='potion of healing', type='other')
i127 = Item(name='pouch', type='other')
i128 = Item(name='quiver', type='other')
i129 = Item(name='ram, portable', type='other')
i130 = Item(name='rations (1 day)', type='other')
i131 = Item(name='robes', type='other')
i132 = Item(name='rope, hempen (50 feet)', type='other')
i133 = Item(name='rope, silk (50 feet)', type='other')
i134 = Item(name='sack', type='other')
i135 = Item(name='scale, merchant\'s', type='other')
i136 = Item(name='sealing wax', type='other')
i137 = Item(name='shovel', type='other')
i138 = Item(name='signal whistle', type='other')
i139 = Item(name='signet ring', type='other')
i140 = Item(name='soap', type='other')
i141 = Item(name='spellbook', type='other')
i142 = Item(name='spikes, iron (10)', type='other')
i143 = Item(name='spyglass', type='other')
i144 = Item(name='tent (two-person)', type='other')
i145 = Item(name='tinderbox', type='other')
i146 = Item(name='torch', type='other')
i147 = Item(name='vial', type='other')
i148 = Item(name='waterskin', type='other')
i149 = Item(name='whetstone', type='other')
i150 = Item(name='bagpipes', type='instrument')
i151 = Item(name='drum', type='instrument')
i152 = Item(name='dulcimer', type='instrument')
i153 = Item(name='flute', type='instrument')
i154 = Item(name='lute', type='instrument')
i155 = Item(name='lyre', type='instrument')
i156 = Item(name='horn', type='instrument')
i157 = Item(name='pan flute', type='instrument')
i158 = Item(name='shawm', type='instrument')
i159 = Item(name='viol', type='instrument')
i160 = Item(name='alchemist\'s supplies', type='artisan\'s tools')
i161 = Item(name='brewer\'s supplies', type='artisan\'s tools')
i162 = Item(name='calligrapher\'s supplies', type='artisan\'s tools')
i163 = Item(name='carpenter\'s tools', type='artisan\'s tools')
i164 = Item(name='cartographer\'s tools', type='artisan\'s tools')
i165 = Item(name='cobbler\'s tools', type='artisan\'s tools')
i166 = Item(name='cook\'s utensils', type='artisan\'s tools')
i167 = Item(name='glassblower\'s tools', type='artisan\'s tools')
i168 = Item(name='jeweler\'s tools', type='artisan\'s tools')
i169 = Item(name='leatherworker\'s tools', type='artisan\'s tools')
i170 = Item(name='mason\'s tools', type='artisan\'s tools')
i171 = Item(name='painter\'s supplies', type='artisan\'s tools')
i172 = Item(name='potter\'s tools', type='artisan\'s tools')
i173 = Item(name='smith\'s tools', type='artisan\'s tools')
i174 = Item(name='tinker\'s tools', type='artisan\'s tools')
i175 = Item(name='weaver\'s tools', type='artisan\'s tools')
i176 = Item(name='woodcarver\'s tools', type='artisan\'s tools')
i177 = Item(name='dice set', type='gaming set')
i178 = Item(name='dragonchess set', type='gaming set')
i179 = Item(name='playing card set', type='gaming set')
i180 = Item(name='three-dragon ante set', type='gaming set')
i181 = Item(name='disguise kit', type='other tools')
i182 = Item(name='forgery kit', type='other tools')
i183 = Item(name='herbalism kit', type='other tools')
i184 = Item(name='navigator\'s tools', type='other tools')
i185 = Item(name='poisoner\'s kit', type='other tools')
i186 = Item(name='thieves\' tools', type='other tools')
i187 = Item(name='camel', type='mounts and other animals')
i188 = Item(name='donkey or mule', type='mounts and other animals')
i189 = Item(name='elephant', type='mounts and other animals')
i190 = Item(name='horse, draft', type='mounts and other animals')
i191 = Item(name='horse, riding', type='mounts and other animals')
i192 = Item(name='mastiff', type='mounts and other animals')
i193 = Item(name='poney', type='mounts and other animals')
i194 = Item(name='warhorse', type='mounts and other animals')
i195 = Item(name='galley', type='waterborne vehicles')
i196 = Item(name='keelboat', type='waterborne vehicles')
i197 = Item(name='longship', type='waterborne vehicles')
i198 = Item(name='rowboat', type='waterborne vehicles')
i199 = Item(name='sailing ship', type='waterborne vehicles')
i200 = Item(name='war ship', type='waterborne vehicles')
i201 = Item(name='1 lb. of wheat', type='trade goods')
i202 = Item(name='1 lb. of flower or one chicken', type='trade goods')
i203 = Item(name='1 lb. of salt', type='trade goods')
i204 = Item(name='1 lb. of iron or 1 sq. yd. of canvas', type='trade goods')
i205 = Item(name='1 lb. of copper or 1 sq. yd. of cotton', type='trade goods')
i206 = Item(name='1 lb. of ginger or one goat', type='trade goods')
i207 = Item(name='1 lb. of cinnamon or pepper or one sheep', type='trade goods')
i208 = Item(name='1 lb. of clothes or one pig', type='trade goods')
i209 = Item(name='1 lb. of silver or 1 sq. yd. of linen', type='trade goods')
i210 = Item(name='1 sq. ft. of silk or one cow', type='trade goods')
i211 = Item(name='1 lb. of saffron or one ox', type='trade goods')
i212 = Item(name='1 lb. of gold', type='trade goods')
i213 = Item(name='1 lb. of platinum', type='trade goods')
i214 = Item(name='explorer\'s pack', type='starting pack')
i215 = Item(name='diplomat\'s pack', type='starting pack')
i216 = Item(name='entertainer\'s pack', type='starting pack')
i217 = Item(name='priest\'s pack', type='starting pack')
i218 = Item(name='dungeoneer\'s pack', type='starting pack')
i219 = Item(name='burglar\'s pack', type='starting pack')
i220 = Item(name='scholar\'s pack', type='starting pack')

items = [
	i1,i2,i3,i4,i5,i6,i7,i8,i9,i10,
	i11,i12,i13,i14,i15,i16,i17,i18,i19,i20,
	i21,i22,i23,i24,i25,i26,i27,i28,i29,i30,
	i31,i32,i33,i34,i35,i36,i37,i38,i39,i40,
	i41,i42,i43,i44,i45,i46,i47,i48,i49,i50,
	i51,i52,i53,i54,i55,i56,i57,i58,i59,i60,
	i61,i62,i63,i64,i65,i66,i67,i68,i69,i70,
	i71,i72,i73,i74,i75,i76,i77,i78,i79,i80,
	i81,i82,i83,i84,i85,i86,i87,i88,i89,i90,
	i91,i92,i93,i94,i95,i96,i97,i98,i99,i100,
	i101,i102,i103,i104,i105,i106,i107,i108,i109,i110,
	i111,i112,i113,i114,i115,i116,i117,i118,i119,i120,
	i121,i122,i123,i124,i125,i126,i127,i128,i129,i130,
	i131,i132,i133,i134,i135,i136,i137,i138,i139,i140,
	i141,i142,i143,i144,i145,i146,i147,i148,i149,i150,
	i151,i152,i153,i154,i155,i156,i157,i158,i159,i160,
	i161,i162,i163,i164,i165,i166,i167,i168,i169,i170,
	i171,i172,i173,i174,i175,i176,i177,i178,i179,i180,
	i181,i182,i183,i184,i185,i186,i187,i188,i189,i190,
	i191,i192,i193,i194,i195,i196,i197,i198,i199,i200,
	i201,i202,i203,i204,i205,i206,i207,i208,i209,i210,
	i211,i212
]

db.session.add_all(items)
db.session.commit()