"""empty message

Revision ID: f565769be4b7
Revises: 
Create Date: 2019-11-05 12:48:20.796768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f565769be4b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('creating_this_class', sa.String(length=2500), nullable=True),
    sa.Column('hit_dice', sa.String(length=7), nullable=True),
    sa.Column('alt_hit_points_at_higher_levels', sa.Integer(), nullable=True),
    sa.Column('specialty_header', sa.String(length=30), nullable=True),
    sa.Column('specialty_description', sa.String(length=2000), nullable=True),
    sa.Column('extra_information', sa.String(length=2500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('class_specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=3000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('discreet_level_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('features', sa.String(length=50), nullable=True),
    sa.Column('rages', sa.Integer(), nullable=True),
    sa.Column('rage_damage', sa.Integer(), nullable=True),
    sa.Column('martial_arts', sa.String(length=7), nullable=True),
    sa.Column('ki_points', sa.Integer(), nullable=True),
    sa.Column('unarmored_movement', sa.Integer(), nullable=True),
    sa.Column('sneak_attack', sa.String(length=7), nullable=True),
    sa.Column('cantrips_known', sa.Integer(), nullable=True),
    sa.Column('spells_known', sa.Integer(), nullable=True),
    sa.Column('sorcerer_points', sa.Integer(), nullable=True),
    sa.Column('spell_slots', sa.Integer(), nullable=True),
    sa.Column('slot_level', sa.Integer(), nullable=True),
    sa.Column('invocations_known', sa.Integer(), nullable=True),
    sa.Column('slots_for_1st', sa.Integer(), nullable=True),
    sa.Column('slots_for_2nd', sa.Integer(), nullable=True),
    sa.Column('slots_for_3rd', sa.Integer(), nullable=True),
    sa.Column('slots_for_4th', sa.Integer(), nullable=True),
    sa.Column('slots_for_5th', sa.Integer(), nullable=True),
    sa.Column('slots_for_6th', sa.Integer(), nullable=True),
    sa.Column('slots_for_7th', sa.Integer(), nullable=True),
    sa.Column('slots_for_8th', sa.Integer(), nullable=True),
    sa.Column('slots_for_9th', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eldritch_invocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_level', sa.Integer(), nullable=True),
    sa.Column('prerequisite_spell', sa.Integer(), nullable=True),
    sa.Column('prerequisite_specialty', sa.Integer(), nullable=True),
    sa.Column('prerequisite_pact', sa.String(length=25), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('origin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('traits_description', sa.String(length=120), nullable=True),
    sa.Column('improved_strength', sa.Integer(), nullable=True),
    sa.Column('improved_dexterity', sa.Integer(), nullable=True),
    sa.Column('improved_constitution', sa.Integer(), nullable=True),
    sa.Column('improved_intelligence', sa.Integer(), nullable=True),
    sa.Column('improved_wisdom', sa.Integer(), nullable=True),
    sa.Column('improved_charisma', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(length=280), nullable=True),
    sa.Column('alignment', sa.String(length=360), nullable=True),
    sa.Column('build', sa.String(length=120), nullable=True),
    sa.Column('size_type', sa.String(length=15), nullable=True),
    sa.Column('base_speed', sa.String(length=120), nullable=True),
    sa.Column('subrace_description', sa.String(length=360), nullable=True),
    sa.Column('extra_information', sa.String(length=2500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('ability', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('school', sa.Integer(), nullable=True),
    sa.Column('castingtime', sa.String(length=95), nullable=True),
    sa.Column('ritual', sa.Boolean(), nullable=True),
    sa.Column('concentration', sa.Boolean(), nullable=True),
    sa.Column('range', sa.Integer(), nullable=True),
    sa.Column('area_of_effect', sa.String(length=30), nullable=True),
    sa.Column('verbal', sa.Boolean(), nullable=True),
    sa.Column('somatic', sa.Boolean(), nullable=True),
    sa.Column('materials', sa.String(length=350), nullable=True),
    sa.Column('duration', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_spell_level'), 'spell', ['level'], unique=False)
    op.create_table('breath_weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('dragon', sa.String(length=8), nullable=True),
    sa.Column('damage_type', sa.String(length=12), nullable=True),
    sa.Column('breath_weapon', sa.String(length=16), nullable=True),
    sa.Column('save', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_discreet_list',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('discreet_level_features_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['discreet_level_features_id'], ['discreet_level_features.id'], ),
    sa.PrimaryKeyConstraint('class_id', 'discreet_level_features_id')
    )
    op.create_table('class_specialty_discreet_list',
    sa.Column('class_specialty_id', sa.Integer(), nullable=False),
    sa.Column('discreet_level_features_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_specialty_id'], ['class_specialty.id'], ),
    sa.ForeignKeyConstraint(['discreet_level_features_id'], ['discreet_level_features.id'], ),
    sa.PrimaryKeyConstraint('class_specialty_id', 'discreet_level_features_id')
    )
    op.create_table('class_specialty_list',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['class_specialty_id'], ['class_specialty.id'], ),
    sa.PrimaryKeyConstraint('class_id', 'class_specialty_id')
    )
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('prerequisite', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('list_by_category', sa.String(length=64), nullable=True),
    sa.Column('improved_strength', sa.Integer(), nullable=True),
    sa.Column('improved_dexterity', sa.Integer(), nullable=True),
    sa.Column('improved_constitution', sa.Integer(), nullable=True),
    sa.Column('improved_intelligence', sa.Integer(), nullable=True),
    sa.Column('improved_wisdom', sa.Integer(), nullable=True),
    sa.Column('improved_charisma', sa.Integer(), nullable=True),
    sa.Column('improved_ability_choice', sa.Boolean(), nullable=True),
    sa.Column('ability_improvement_acceptions', sa.String(length=19), nullable=True),
    sa.Column('number_of', sa.Integer(), nullable=True),
    sa.Column('dragon_ancestry', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['origin_id'], ['origin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spells_by_class_list',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('spell_id', 'class_id')
    )
    op.create_table('subrace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=2500), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('subrace_id', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['subrace_id'], ['subrace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_feature_list',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.PrimaryKeyConstraint('class_id', 'feature_id')
    )
    op.create_table('feature_items_list',
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('feature_id', 'item_id')
    )
    op.create_table('feature_skills_list',
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('feature_id', 'skill_id')
    )
    op.create_table('race_feature_list',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('race_id', 'feature_id')
    )
    op.create_table('specialty_feature_list',
    sa.Column('class_specialty_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_specialty_id'], ['class_specialty.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.PrimaryKeyConstraint('class_specialty_id', 'feature_id')
    )
    op.create_table('spells_by_attack_or_save_list',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('spell_id', 'feature_id')
    )
    op.create_table('spells_by_effect_type_list',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('spell_id', 'feature_id')
    )
    op.create_table('subrace_feature_list',
    sa.Column('subrace_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['subrace_id'], ['subrace.id'], ),
    sa.PrimaryKeyConstraint('subrace_id', 'feature_id')
    )
    op.create_table('character_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['class_specialty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_trait',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=360), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_trait')
    op.drop_table('character_class')
    op.drop_table('subrace_feature_list')
    op.drop_table('spells_by_effect_type_list')
    op.drop_table('spells_by_attack_or_save_list')
    op.drop_table('specialty_feature_list')
    op.drop_table('race_feature_list')
    op.drop_table('feature_skills_list')
    op.drop_table('feature_items_list')
    op.drop_table('class_feature_list')
    op.drop_table('character')
    op.drop_table('subrace')
    op.drop_table('spells_by_class_list')
    op.drop_table('feature')
    op.drop_table('class_specialty_list')
    op.drop_table('class_specialty_discreet_list')
    op.drop_table('class_discreet_list')
    op.drop_table('breath_weapon')
    op.drop_index(op.f('ix_spell_level'), table_name='spell')
    op.drop_table('spell')
    op.drop_table('skill')
    op.drop_table('race')
    op.drop_table('origin')
    op.drop_table('item')
    op.drop_table('eldritch_invocation')
    op.drop_table('discreet_level_features')
    op.drop_table('class_specialty')
    op.drop_table('class')
    # ### end Alembic commands ###
